### PR TITLE
Implement memory struct

### PR DESCRIPTION
**Pull request by lucasscharenbroch**
I translated most of this from nes_emu_rust, added some extra testers.

### CODE REVIEW

**Comment by rudy-pants** [comment]
How are you primarily testing your code? I am trying to run memory_test.js and cpu_test.js through Node.js and I cannot test them because the files do not export or import their functions/classes.

**Comment by lucasscharenbroch** [comment]
I'm not familiar with Node.js; if you call [runMemoryTests()](https://github.com/rudyb2001/js-nes-emulator/blob/4dfd8210c0967a075312fd292675c6a2ff238145/memory_test.js#L440) from memory_test.js, an error will be thrown if a test fails.
I import all of the .js files into a .html file and run it from there.

**Comment by rudy-pants** [comment]
Node.js is just a runtime engine for JavaScript, allowing you to run JS code scripts like python code through a command like "node memory_test.js". How are you currently running the test files?

**Comment by lucasscharenbroch** [comment]
I import all of the .js files into a .html file and run it in the browser.

**Comment by rudy-pants** [comment]
Interesting, would it be possible for you to include that .html file so that other people can run the tests? It seems like Node js might be a bit janky for me right now

**Comment by lucasscharenbroch** [comment]
Done.

**Pull request closed without merging**
